business_profile = [
    "company_popular_name",
    "location",
    "company_registered_name",
    "is_active",
    "organisation_name",
    "company_type",
    "market_place_company_id",
    "base_employee_code",
    "total_staff",
    "active_staff",
    "pending_staff",
    "declined_staff",
    # "removed_staff",
    # "requested_resign_staff",
    # "approved_resign_staff",
    # "company_logo",
    "industry",
    {
        "manager_profile": [
            "name",
            "user_id",
            "employment_type",
            "location",
            "employee_code",
            "mobile",
            "is_active",
            "email",
            "employee_id",
            "from_date",
            "to_date",
            "user_role",
        ],
    },
]

business_staff = [
    "name",
    "mobile",
    "email",
    "is_active",
    "employee_id",
    "location",
    "employee_code",
    # "active_from_date",
    # "active_to_date",
    "designation",
    "status",
    "payout_type",
    "salary",
    "managed_from_date",
    "attendance_configuration",
    "user_id",
    "employement_type",
    "joining_date",
    "employement_accepted_date",
    "department_name",
    "user_role",
    "reporting_to",
    {
        "company_profile": [
            "name",
            "company_id" "is_active",
            "from_date",
            "company_type",
            "to_date",
            "location",
        ],
    },
]

attendance = [
    "company_name",
    "company_type",
    "industry",
    "org",
    "location",
    "company_id",
    "staff_name",
    "staff_id",
    "created_at",
    "actual_punch_in_time",
    "actual_punch_out_time",
    "updated_at",
    "is_present",
    "is_absent",
    "on_leave",
    "on_half_day_leave",
    "is_overtime",
    "overtime_hours",
    "punch_in",
    "punch_out",
    "leave_type",
    "is_late_fine",
    "late_fine_hours",
    "overtime_rate",
    "late_fine_rate",
    "total_payout",
    "makred_by_role",
]


payslip = [
    "company_name",
    "company_id",
    "staff_name",
    "staff_id",
    "payslip_id",
    "payout_type",
    "payout_amount",
    "created_at",
    "updated_at",
    "total_present",
    "total_leave",
    "total_absent",
    "overtime_amount",
    "paid_by",
    "deducted_amount",
    "is_active",
    "location",
    "late_fine",
    "bonus",
    "allowance",
    "designation",
    "generated_from_date",
    "generated_to_date",
    "pf_amount",
    "esic_amount",
]
